site_name: 计算生物/生物信息PhD申请指北
theme:
  name: material
  language: zh
  palette:

    # Toggle light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    # Toggle dark mode
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

nav:
  - 致读者: index.md
  - 申请前准备: Preparation.md
  - 项目介绍与选校建议: Program_list.md
  - 文书: PS_CV.md
  - 面试: interview.md
  - 申请案例: example.md
  - 致谢: acknowledge.md
  - 其他资源: other_resource.md
  - License: license.md